# Generated by Django 4.0.3 on 2022-05-18 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewPageModel',
            fields=[
                ('name', models.CharField(help_text='Enter a name for the field.', max_length=100)),
                ('contents', models.TextField(help_text='Enter title and contents for page in markdown language.')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
